const DB_ERRORS = {
    UNIQUE_CONSTRAINT_ERROR: 'UNIQUE_CONSTRAINT_ERROR',
    FOREIGN_KEY_CONSTRAINT_ERROR: 'FOREIGN_KEY_CONSTRAINT_ERROR', 
    GENERIC_ERROR: 'GENERIC_ERROR'
};

const DB_ERROR_CODES = {
    SQLITE_CONSTRAINT: 'SQLITE_CONSTRAINT'
}

module.exports = { DB_ERRORS, DB_ERROR_CODES };