const CREATE_USER_TABLE = `
CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
)
`;

const CREATE_COUPON_TABLE = `
CREATE TABLE IF NOT EXISTS coupon (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code VARCHAR(255) NOT NULL,
    expiry INTEGER NOT NULL,
    ownerId INTEGER NOT NULL,
    CONSTRAINT owner FOREIGN KEY(ownerId) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE
)
`;

module.exports = { CREATE_USER_TABLE, CREATE_COUPON_TABLE };